GET https://api.github.com/search/repositories?q=language:go&page=34 HTTP/1.1
Accept: application/vnd.github.mercy-preview+json

###
GET https://api.github.com/repos/kubernetes/kubernetes/contents HTTP/1.1
Accept: application/vnd.github.VERSION.raw

###
GET https://api.github.com/repositories HTTP/1.1
Accept: application/vnd.github.VERSION.raw

###
GET https://raw.githubusercontent.com/kubernetes/kubernetes/master/go.mod HTTP/1.1
Accept: application/vnd.github.VERSION.raw

###
GET https://api.github.com/repos/kubernetes/kubernetes/contents/go.mod HTTP/1.1
Accept: application/vnd.github.VERSION.raw
